### ISSUE TITLE
Derived Futures

### ISSUE THREAD

**Issue by benbayard** [UrbanDoor/mobx-failable#2]
## Problem
Data in modern JS eco systems is often very fluid, the data that UIs need is not always the data that your APIs provide. 

Let's say I have:
```ts
const asyncDates = new Failable<Date[]>();
```
and I want to convert that to an array of locale date strings:
```ts
const localeDateStrings = asyncDates.match({
  success:(dates) => new Failable<string[]>().success(dates.map(d => d.toLocaleDateString())), 
  pending: () => asyncDates,
  error: () => asyncDates,
})
```
However, this has a few problems. 
1. The type of `localeDateStrings` is `Failable<Date[]> | Failable<string[]>`
2. If you call `localeDateStrings.accept(Promise.resolve(...))`, the output you get and the input you can provide is unexpected. 

## Proposal 
To solve this we should have a new method on a `Failable` and `Loadable` that returns a `ReadonlyFailable` (I like to call it `DerivedFuture`).

The semantics of derive would be roughly: pass an object. 
* if the object is empty, return this.
    * then for each state in the object (all of which are optional): if the state is absent, return this
* if the state has a function: call the function with the right data
* if the function returns, transform to a success
* if the function throws, transform to a failure
* if you want pending to be untransformed by derive, don't specify a function at all
This also lets you transform across states:

```ts
d.derive({success: () => {throw new TypeError})
``` 
will turn yield a failure from a success.
the opposite is true: 

```ts
d.derive({failure: () => 'defaultValue'})
```` 
will yield a success from a failure.

Usage would look something like this: 

```ts
class S { 
  @observable d = new Failable<string>(); 
  @computed get e() { return d.derive(...); } 
}
```

**Comment by kourge** [comment]
Here are some architectural sketches.

### `ReadonlyFuture<T>`

This is similar to `Future<T>` but with all its mutative methods removed.

### `DerivedFailable<T>` / `DerivedLoadable<T>`

These would be hidden, unexported class implementations that fulfill `ReadonlyFuture<T>`, returned by the newly-proposed `derive` method.

### `DeriveOptions`

Initially I thought of `DeriveOptions` as similar to `MatchOptions`, except every callback is optional:

```ts
export interface DeriveOptions<T, A, B, C> {
  success?: (data: T) => A;
  failure?: (error: Error) => B;
  pending?: () => C;
}
```

Having attempted a proof of concept implementation, I'd say this introduces an explosion of complexity that we shouldn't have to deal with, since this variant allows each callback to produce different return types. This is what I call _polymorphic derivation_:

```ts
declare const f: Failable<Date>;
const g = f.derive({
  success: date => date.toString(),
  failure: error => -1,
  pending: () => false
});
// g: Failable<string | number | boolean>
```

My proposed simplification is _monomorphic derivation_:

```ts
export interface DeriveOptions<From, To> {
  success?: (data: From) => To;
  failure?: (error: Error) => To;
  pending?: () => To;
}
```

I suspect any possible use case of polymorphic derivation can be replaced by chaining a `match` call after `derive`.

Here are also some unresolved problems questions that will become clear as I attempt to implement this:
- The current proposal says given `f: Failable<T>`, `f.derive({})` will return a `ReadonlyFuture<T>` that has the same identity as `f`. Does the TypeScript method overload system allow this? One possible complication is that the type system does not allow us to express an empty object like Flow does; `{}` is more or less interchangeable with `any`.
- The current proposed form of `DeriveOptions` is a weak type (i.e. every property is optional). Realistically when we `derive`, there is always at least one state that gets handled. Should it be rewritten into a union of three types? (e.g. `{success, failure?, pending?} | {success?, failure, pending?} | {success?, failure?, pending}`) Whether this is needed is also entangled with how the previous bullet point gets resolved.
- Further shorthands? For example, `.map(f)` can expand to `.derive({success: f})`, `.catch(f)` to `.derive({failure: f})`.

**Comment by benbayard** [comment]
All of this sounds good to me @kourge . Do @squirly or @SashaBayan have any additional input? Otherwise I say this is a fantastic way to go :D

**Comment by kourge** [comment]
Completed via #3.
